### ISSUE TITLE
The Player never fights back in combat, even if able

### ISSUE THREAD

**Issue by Cerapter** [Fifth-Aeon/CCG-Model#21]
The Player, being a child object of the Unit, has a damage value, and it can be increased by other cards. Despite this, the Player never deals damage back in combat.

This is caused by [`resolveCombat()`](https://github.com/Fifth-Aeon/CCG-Model/blob/master/clientGame.ts#L408) method not falling back to the already existing `attacker.fight()` method to deal damage to the Player, instead replicating said method in-place.

As the Player is a child of Unit, it could be passed as the `target` parameter in the method -- but attention should be paid to the method exhausting the target. It may need a special exception, though `canActivate()` (returns the opposite value of the `exhausted` field of a Unit) is used nowhere, so it shouldn't cause problems.

**Comment by WilliamRitson** [comment]
The player not retaliating was an intentional choice as I did not consider players retaliating to be part of the game's rules. But on examination, I think your right, given that it would be pretty easy to program and custom cards might make use of it. I will look into changing it soon (feel free to submit a pull request if you have a working version with the change).
